import { FileCheck2, LockKeyhole, Scale, ShieldCheck } from 'lucide-react'
import { AgreementLookup } from '../components/AgreementLookup'
import { WorkflowProgress } from '../components/WorkflowProgress'
import { gen, useWearline } from '../context/WearlineContext'
import { sha256File } from '../lib/hash'
export function AgreementPage(){
 const w=useWearline(); const a=w.agreement; const loaded=Boolean(a&&a.id===w.agreementId)
 return <section className="page section-pad">
  <div className="page-heading"><span className="kicker">Agreement</span><h1>Freeze the terms before the dispute.</h1><p>Agreement state remains authoritative on StudioNet. Create, inventory, seal and fund without changing the deployed contract.</p></div>
  <AgreementLookup/>
  {loaded&&a?<>
   <section className="surface agreement-summary"><div><span className="muted-label">Agreement #{a.id}</span><h2>{a.property_label}</h2><div className="address-grid"><div><span>Owner</span><code>{a.owner}</code></div><div><span>Renter</span><code>{a.renter}</code></div></div></div><span className="status-pill">{a.status.replaceAll('_',' ')}</span></section>
   <section className="surface"><WorkflowProgress/><div className="rule-grid"><article><LockKeyhole/><span>Deposit</span><strong>{gen(a.deposit_required)}</strong><small>Funded {gen(a.deposit_funded)}</small></article><article><FileCheck2/><span>Inventory</span><strong>{a.item_count} items</strong><small>{a.adjudicated_count} adjudicated</small></article><article><Scale/><span>Frozen policy</span><strong>25 / 60 / 100%</strong><small>Severity 1 / 2 / 3 for new damage</small></article><article><ShieldCheck/><span>Inconclusive</span><strong>{w.unresolved?'Waiver required':'Fail closed'}</strong><small>{w.unresolved} unresolved</small></article></div></section>
   <section className="surface policy-card"><span className="muted-label">Frozen normal-wear policy</span><p>{a.policy_text}</p></section>
   <section className="surface"><div className="section-title"><div><span className="kicker">Inventory</span><h2>Baseline items</h2></div></div>{w.items.length?<div className="inventory-list">{w.items.map(i=><article key={i.index}><span className="item-number">{String(i.index+1).padStart(2,'0')}</span><div><strong>{i.label}</strong><code title={i.baseline_sha256}>sha256 · {i.baseline_sha256.slice(0,16)}…</code></div><span>{gen(i.max_deduction)} cap</span></article>)}</div>:<div className="empty-state">No inventory items yet.</div>}</section>
   <section className="surface"><div className="section-title"><div><span className="kicker">Owner & renter actions</span><h2>Advance the lifecycle</h2></div></div><div className="workflow-actions"><button className="primary-button" disabled={w.busy||!w.owner||a.status!=='DRAFT'||!w.items.length} onClick={()=>void w.transact('seal_agreement',[w.agreementId]).catch(e=>w.setError(e instanceof Error?e.message:String(e)))}>Seal agreement</button><button className="secondary-button" disabled={w.busy||!w.renterRole||a.status!=='SEALED'} onClick={()=>void w.transact('fund_agreement',[w.agreementId],a.deposit_required).catch(e=>w.setError(e instanceof Error?e.message:String(e)))}>Fund exact deposit · {gen(a.deposit_required)}</button></div></section>
  </>:<div className="empty-state large">Connect a StudioNet wallet and load an agreement, or create a new one below.</div>}
  {(!a||a.id!==w.agreementId||a.status==='DRAFT')&&<form className="surface action-card" onSubmit={w.createAgreement}><div className="form-intro"><span className="kicker">Create on chain</span><h2>New agreement</h2><p>Property and renter details share the first row. The frozen wear policy spans the full form width.</p></div><div className="form-grid"><label>Property label<input required minLength={3} value={w.property} onChange={e=>w.setProperty(e.target.value)}/></label><label>Renter address<input required value={w.renter} onChange={e=>w.setRenter(e.target.value)} placeholder="0x…"/></label><label className="compact-field">Deposit (GEN)<input required value={w.deposit} onChange={e=>w.setDeposit(e.target.value)} placeholder="1.00"/></label><label className="wide">Frozen normal-wear policy<textarea required minLength={20} value={w.policy} onChange={e=>w.setPolicy(e.target.value)}/></label></div><div className="form-actions"><button className="primary-button" disabled={w.busy||!w.client||!w.live}>{w.busy?'Transaction pending…':'Create agreement'}</button></div></form>}
  {loaded&&a&&w.owner&&a.status==='DRAFT'&&<form className="surface action-card" onSubmit={w.addItem}><div className="form-intro"><span className="kicker">Inventory baseline</span><h2>Add a hash-bound item</h2></div><div className="form-grid"><label>Item label<input required minLength={2} value={w.label} onChange={e=>w.setLabel(e.target.value)}/></label><label className="compact-field">Maximum deduction (GEN)<input required value={w.cap} onChange={e=>w.setCap(e.target.value)} placeholder="0.25"/></label><label className="wide">Baseline HTTPS URL<input required type="url" value={w.baselineUrl} onChange={e=>w.setBaselineUrl(e.target.value)} placeholder="https://…"/></label><label className="wide">Baseline SHA-256<input required value={w.baselineHash} onChange={e=>w.setBaselineHash(e.target.value)} placeholder="64 hexadecimal characters"/></label></div><div className="workflow-actions"><button type="button" className="secondary-button" disabled={!w.baselineUrl} onClick={()=>void w.hashUrl(w.baselineUrl,w.setBaselineHash)}>Hash URL bytes</button><label className="file-button">Hash local image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(f)w.setBaselineHash(await sha256File(f))}}/></label><button className="primary-button" disabled={w.busy||!w.client}>{w.busy?'Transaction pending…':'Add item'}</button></div></form>}
 </section>
}
