import { AgreementLookup } from '../components/AgreementLookup'
import { digest, evidenceUrl, gen, useWearline } from '../context/WearlineContext'
import { sha256File } from '../lib/hash'
export function EvidencePage(){
 const w=useWearline(); const a=w.agreement; const loaded=Boolean(a&&a.id===w.agreementId)
 return <section className="page section-pad">
  <div className="page-heading"><span className="kicker">Evidence</span><h1>Compare what changed.</h1><p>Baseline and checkout evidence stay visually central while classification, rationale and deductions remain readable.</p></div>
  {!w.agreementId&&<AgreementLookup/>}
  {w.agreementId&&!loaded&&<><AgreementLookup/><div className="empty-state large">{w.loading?'Reading agreement from StudioNet…':'Load this agreement to inspect evidence.'}</div></>}
  {loaded&&a&&<div className="review-list">{w.items.length===0?<div className="empty-state large">No inventory items are attached to this agreement.</div>:w.items.map(item=><article className="review-card" key={item.index}>
   <div className="review-head"><div><span className="item-number">{String(item.index+1).padStart(2,'0')}</span><div><h2>{item.label}</h2><span>{gen(item.max_deduction)} frozen cap</span></div></div><span className={'class-pill '+(item.classification?item.classification.toLowerCase().replace('_','-'):'inconclusive')}>{item.classification||'Awaiting review'}</span></div>
   <div className="image-pair">{[['Baseline',item.baseline_url,item.baseline_sha256],['Checkout',item.checkout_url,item.checkout_sha256]].map(([title,src,hash])=><div className="evidence-image" key={title}><span>{title}</span>{src?<a href={src} target="_blank" rel="noreferrer"><img src={src} alt={title+' evidence for '+item.label} loading="lazy"/></a>:<div className="image-empty">Checkout evidence not submitted</div>}<code title={hash}>{hash?'sha256 · '+hash.slice(0,16)+'…':'No digest'}</code></div>)}</div>
   <div className="adjudication-grid"><div><span>Classification</span><strong>{item.classification||'Pending'}</strong></div><div><span>Severity</span><strong>{item.severity}</strong></div><div><span>Deduction</span><strong>{gen(item.deduction)}</strong></div><div><span>Action state</span><strong>{item.waived?'Owner waived':item.adjudicated?'Adjudicated':'Pending'}</strong></div></div>
   <div className="rationale"><span>Validator rationale</span><p>{item.rationale||'The item has not been adjudicated.'}</p></div>
   {!item.adjudicated&&w.renterRole&&['FUNDED','REVIEWING'].includes(a.status)&&<div className="item-form"><label>Checkout HTTPS URL<input type="url" value={w.checkoutUrls[item.index]??item.checkout_url} onChange={e=>w.setCheckoutUrls({...w.checkoutUrls,[item.index]:e.target.value})}/></label><label>Checkout SHA-256<input value={w.checkoutHashes[item.index]??item.checkout_sha256} onChange={e=>w.setCheckoutHashes({...w.checkoutHashes,[item.index]:e.target.value})}/></label><div className="workflow-actions"><button className="secondary-button" type="button" onClick={()=>void w.hashUrl(w.checkoutUrls[item.index]??item.checkout_url,h=>w.setCheckoutHashes({...w.checkoutHashes,[item.index]:h}))}>Hash URL bytes</button><label className="file-button">Hash local image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(f)w.setCheckoutHashes({...w.checkoutHashes,[item.index]:await sha256File(f)})}}/></label><button className="primary-button" type="button" disabled={w.busy} onClick={()=>void (async()=>{try{await w.transact('submit_checkout',[w.agreementId,item.index,evidenceUrl(w.checkoutUrls[item.index]??item.checkout_url),digest(w.checkoutHashes[item.index]??item.checkout_sha256)])}catch(e){w.setError(e instanceof Error?e.message:String(e))}})()}>Submit checkout</button></div></div>}
   {!item.adjudicated&&item.checkout_url&&<button className="primary-button" disabled={w.busy} onClick={()=>void w.transact('adjudicate_item',[w.agreementId,item.index]).catch(e=>w.setError(e instanceof Error?e.message:String(e)))}>Run consensus adjudication</button>}
   {w.owner&&item.adjudicated&&item.classification==='INCONCLUSIVE'&&!item.waived&&<button className="secondary-button" disabled={w.busy} onClick={()=>void w.transact('waive_inconclusive',[w.agreementId,item.index]).catch(e=>w.setError(e instanceof Error?e.message:String(e)))}>Owner waiver · zero deduction</button>}
  </article>)}</div>}
 </section>
}
